name: Docker build and push

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  push:
    tags:
      - '*'

jobs:
  docker-build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Frontend
        run: docker build -t $DOCKER_USERNAME/filesox-front:latest" -f docker/front/Dockerfile .

      - name: Push Frontend
        run: docker push $DOCKER_USERNAME/filesox-front:latest"

  docker-build-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Backend
        run: docker build -t $DOCKER_USERNAME/filesox-back:latest" -f docker/back/Dockerfile .

      - name: Push Backend
        run: docker push $DOCKER_USERNAME/filesox-back:latest"
