name: Docker build and push

on:
  push:
    tags:
      - '*'

jobs:
  docker-build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Frontend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker build -t ${DOCKER_USERNAME}/filesox-front:latest -f docker/front/Dockerfile .

      - name: Push Frontend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker push ${DOCKER_USERNAME}/filesox-front:latest

  docker-build-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Backend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker build -t ${DOCKER_USERNAME}/filesox-back:latest -f docker/back/Dockerfile .

      - name: Push Backend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker push ${DOCKER_USERNAME}/filesox-back:latest