name: Docker build and push

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_URL: ${{ secrets.DOCKER_PASSWORD }}

on:
  push:
    tags:
      - '*'

jobs:
  docker-build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Frontend
        run: docker build . -f docker/front/Dockerfile -t $DOCKER_URL/filesox-front:latest

      - name: Push Frontend
        run: docker push$DOCKER_URL/filesox-front:latest

  docker-build-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Backend
        run: docker build . -f docker/back/Dockerfile -t $DOCKER_URL/filesox-back:latest

      - name: Push Backend
        run: docker push $DOCKER_URL/filesox-back:latest
